### ISSUE TITLE
How do you download this?

### ISSUE THREAD

**Issue by InfornoFire** [LeinneSW/PureEntities#14]
Drop the source, start server, error incomplete api

**Comment by DarkWav** [comment]
# 1. you need pocketmine for php7!

download:https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher/archive/master.zip (download the master)

# 2.you need devtools-plugin:

download:https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher/raw/master/plugins/DevTools-api200.phar

# 3.you must change in plugin.yml:

main: milk.entitymanager.EntityManager

# to

main: milk/entitymanager/EntityManager

# Than it Works!

**Comment by InfornoFire** [comment]
Ahem, mac?

**Comment by InfornoFire** [comment]
Uhh mac?

**Comment by InfornoFire** [comment]
Does it have to be that pocketmine, or can it be ImagicalMine
Plus Im on mac

**Comment by InfornoFire** [comment]
Nvm, I just found out ImagicalMine doesn't use PhP7, CaseClose

**Comment by PocketKiller** [comment]
@InfornoFire ImagicalMine supports PHP7 already..

**Comment by InfornoFire** [comment]
If thats so....

**Comment by InfornoFire** [comment]
Why isnt it working

**Comment by InfornoFire** [comment]
Incompatible api...

**Comment by PocketKiller** [comment]
because you did not use the php7 branch

**Comment by InfornoFire** [comment]
Uhhh, ohh, is it this https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher, if so, Im mac

**Comment by InfornoFire** [comment]
hello?

**Comment by PocketKiller** [comment]
hello

**Comment by DarkWav** [comment]
You want a compiled phar of imagicalmine for php 7? use devtools-api200 , make a source server with this master and do /makeserver __________________           master IM-PHP7: https://github.com/ImagicalMine/ImagicalMine/archive/php7.zip

**Comment by DarkWav** [comment]
if you want a direct download for the phar, i have to ask the IM-Team if i can redistribute my compiled .phar server file

**Comment by DarkWav** [comment]
php7 mac installation: 1. download php 7.0.1  and drag it into you bin/php folder. ( delete everyting tat was in before)
2. download the windows baranch.
3. put everyting wich is is the bin folder of the windows lancher branch wich is not ending on .exe into your bin folder ( from your server )

# IT IS VERY IMPORTANT TO REPLACE FILES, WICH ARE IN THE ORGINAL PHP7 BIARY WITH THE ONES FROM THE WINDOWS POCKETMINE-PHP7 BIN FOLDER

**Comment by RocoWayne** [comment]
use this http://pmt.mcpe.me/

**Comment by InfornoFire** [comment]
Thank you DarkWav

**Comment by InfornoFire** [comment]
Uhh, php 7.0.1 download?

**Comment by InfornoFire** [comment]
Can someone retell this in a more understandable way

**Comment by InfornoFire** [comment]
Can someone also just do it for me

**Comment by InfornoFire** [comment]
ay look https://github.com/ImagicalMine/ImagicalMine/issues/811

**Comment by InfornoFire** [comment]
Hmm, didn't installed binary for php7 lol, uhh

**Comment by InfornoFire** [comment]
Can someone tell me this in a simpler way

**Comment by DarkWav** [comment]
there is no simpler way, its very hard to do this on MAC.

**Comment by robske110** [comment]
Mac =~ Linux

**Comment by InfornoFire** [comment]
Im saying, PUT IT IN UNDERSTANDABLE TERMS not saying your grammar is bad, just need to give more effort into the message.

**Comment by DarkWav** [comment]
[QUOTE="InfermFire"]Im saying, PUT IT IN UNDERSTANDABLE TERMS not saying your grammar is bad, just need to give more effort into the message.[/QUOTE]
wahat isn´t understanable?

**Comment by InfornoFire** [comment]
Uh
So, im saying it doesent work, maybe I read it wrong or not getting the correct links, anywho can you precompile this for me?

**Comment by DarkWav** [comment]
i can compile imagicalmine for  php7 for you , but i must ask on the IM forums if I am allowed to publish this precompiled build. i will ask if i can publish the .phar

**Comment by InfornoFire** [comment]
Well, I apprieate your help

**Comment by DarkWav** [comment]
The download is here: http://forums.imagicalmine.me/threads/temporary-download-link-for-imagicalmine-for-php7-compiled-phar-file.165/#post-947

**Comment by DarkWav** [comment]
download will be avilable until jenkins is not failing anymore.

**Comment by DarkWav** [comment]
or download it direct here: http://simonvogl.de/resources/ImagicalMine-IC-PHP7.phar

**Comment by LeinneSW** [comment]
issue tracker is not a forum. do not spam subscribers' mail list.
