### ISSUE TITLE
No File

### ISSUE THREAD

**Issue by ghost** [LeinneSW/PureEntities#16]
There is no Phar File in the Zip !??

**Comment by PocketKiller** [comment]
of course there isn't, make the zip to phar on http://pmt.mcpe.me close

**Comment by ghost** [comment]
I have install V1.3 
Ist this a newer Version? 
I used it on ImagicalMine.

**Comment by DarkWav** [comment]
This thret should help you: https://github.com/milk0417/EntityManager/issues/14
there is even a download-link for imagicalmine-php7 compiled.

**Comment by ghost** [comment]
ok the newer Version only for PHP7 Imagicalmine !??
I have the php5 Version of imagicalmine

**Comment by InfornoFire** [comment]
Ok heres the rule, theres a php7 revolution thing coming, its a separate branch with different features, note that PLUGINS WILL NOT WORK IF THEY ARE NOT UPDATED TO PHP7, research it yourself, btw get used to this, if you want to download things from Github, download the zip, open it up, take the master and put it in your plugins, SHUT DOWN AND START UP, /reload does not work. The plugin will automatically load and is ready for use. If you want to turn it to .phar for a reason, install dev tools (look it up its a plugin) and do /makeplugin and the name (the name is found in the plugin.yml inside the master) compile it and you will get a .phar of it in the devtools folder.

**Comment by InfornoFire** [comment]
Now, DarkWav, apparently your precompiled .phar still does not work due to the start.sh needing to be updated for max/other things that does not use start.cmd

**Comment by DarkWav** [comment]
the procompiled build is not a full server installation, it is only the ImagicalMine.phar
I will make you a full installation .zip.

**Comment by DarkWav** [comment]
use that one for MacOS: [(Download)](http://www.simonvogl.de/resources/ImagicalMine-PHP7-OSX.zip)

**Comment by DarkWav** [comment]
Christian665, you can download entitymanager here: [(DOWNLOAD)](https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher/raw/master/plugins/EntityManager_v2.4%20Beta.phar)
ImagicalMine php7: [(PHAR DOWNLOAD)](http://simonvogl.de/resources/ImagicalMine-IC-PHP7.phar) [(LAUNCHER FOR POCKETMINE-PHP7 DOWNLOAD)](https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher/archive/master.zip)
Replace the ImagicalMine file in the launcher.
IM-PHP7 for MacOS:  [(DOWNLOAD)](http://www.simonvogl.de/resources/ImagicalMine-PHP7-OSX.zip)

**Comment by ghost** [comment]
for Me is ImagicalMine V1 with the newest Phar File STABLE. IT Works all I need.  Mobs,  weather and performance is so hmm ok :-|

On the ImagicalMine Homepage there ist no PHP7 Version  to download. I use unfortunately XBUNTU Linux ! my Netbook Not so Powerfull and on WinXP ImagicalMine Not Works. 

is the PHP7 Version also stable and also feature like PHP5?
is there a Linux Version ?

thanks

**Comment by PocketKiller** [comment]
@Christian665 there is, PHP7 Branch, try it out, and report me crashes on startup.

**Comment by InfornoFire** [comment]
Thanks DarkWav

**Comment by InfornoFire** [comment]
Uhh, the start.sh now cannot detect the bin files.

**Comment by ghost** [comment]
Self Problem

**Comment by DarkWav** [comment]
Christian665 , download IM-php7-linux here: [(DOWNLOAD)](https://github.com/ecoron/ImagicalMine-php7-linux/releases/download/0.1/ImagicalMine-php7-linux.tar.gz)

**Comment by DarkWav** [comment]
Should be closed.

**Comment by DarkWav** [comment]
PLEASE CLOSE THIS!
