### ISSUE TITLE
Not find the Config

### ISSUE THREAD

**Issue by Erkam246** [LeinneSW/PureEntities#22]
Not generate a config file and this error

10.02 17:01:54 [Server] INFO Warning: file_put_contents(/plugins/EntityManager/drops.yml): failed to open stream: No such file or directory in phar:///imagicalmine_php7.phar/src/pocketmine/utils/Config.php on line 213
10.02 17:01:54 [Server] INFO Warning: file_put_contents(/plugins/EntityManager/spawner.yml): failed to open stream: No such file or directory in phar:///imagicalmine_php7.phar/src/pocketmine/utils/Config.php on line 213
10.02 17:01:54 [Server] INFO Warning: file_put_contents(/plugins/EntityManager/config.yml): failed to open stream: No such file or directory in phar:///imagicalmine_php7.phar/src/pocketmine/utils/Config.php on line 213
10.02 17:01:54 [Server] INFO [16:01:54] system> Enabling EntityManager v2.6

**Comment by DarkWav** [comment]
you must create a folder called "EntityManager in your plugins folder, then the config is being generated.

Should be closed.
