### ISSUE TITLE
Spawn mobs with eggs problem (php5 2.6)

### ISSUE THREAD

**Issue by XiangZhao969** [LeinneSW/PureEntities#29]
Only ocelots and rabbits are able to move. Btw thanks for keep updating this awesome plugin

**Comment by PocketKiller** [comment]
XD

**Comment by XiangZhao969** [comment]
What :v

**Comment by LeinneSW** [comment]
???

**Comment by XiangZhao969** [comment]
... just try to spawn mobs with eggs and you will see that :v

**Comment by LeinneSW** [comment]
?? I tried to test, but move everything properly?

**Comment by XiangZhao969** [comment]
@@ i'm using v2.6 php5. Actually mobs can move when they was spawned by autospawner, but not by eggs

**Comment by XiangZhao969** [comment]
Nvm, somehow it works :v
