### ISSUE TITLE
Server console spam when mobs spawn 

### ISSUE THREAD

**Issue by MasterlazorX** [LeinneSW/PureEntities#31]
So when mobs spawn it would spam the console "Warning: mt_rand() expects parameter 1 to be integer, string given in /Users/User/Downloads/ImagicalMine (SurvivalPro)-php7-0.14/plugins/EntityManager v2.7/src/milk/entitymanager/task/AutoSpawnTask.php on line 16"
Eventually (after 30-45 mins) the server would freeze, and crashes due to the memory overloading related to it.

**Comment by LeinneSW** [comment]
checked config.yml -> autospawn.rand

**Comment by MasterlazorX** [comment]
Oh thanks, i believed i "fixed" it. So the problem was the " changing symbols. So when i changed the rand, the symbol changed from " to ” and i apparently forgot to copy and paste the symbol. Dont ask me why it does, just a Mac thing.

**Comment by MasterlazorX** [comment]
Fixed :)
