### ISSUE TITLE
Where is last release

### ISSUE THREAD

**Issue by Delimer** [LeinneSW/PureEntities#33]
Where I can find last release to install on mpce server?

**Comment by Patra3** [comment]
Here is the current latest release:
https://github.com/milk0417/PureEntities/releases/tag/V2.6

Always check the releases tab on Github.

**Comment by Delimer** [comment]
But the beafore division by PureEntities and EntityManager, I downloaded version 2.7.

**Comment by Tolo0** [comment]
Just download that and put it in ur plugin folder. U don't need the 2 plugins
