### ISSUE TITLE
Is not fixed

### ISSUE THREAD

**Issue by Erkam246** [LeinneSW/PureEntities#39]
Genisys Crash Dump Sat Feb 27 17:41:01 UTC 2016

Error: Class milk\pureentities\entity\monster\flying\Blaze not found
File: /src/spl/BaseClassLoader
Line: 144
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[135] 
[136]           if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137]               $name::onClassLoaded();
[138]           }
[139]  
[140]           $this->classes[] = $name;
[141] 
[142]             return true;
[143]         }elseif($this->getParent() === null){
[144]           throw new ClassNotFoundException("Class $name not found");
[145]         }
[146] 
[147]         return false;
[148]     }
[149] 
[150]     /**
[151]      \* Returns the path for the class, if any
[152]      *
[153]      \* @param string $name
[154]      *

Backtrace:
#0 (): spl_autoload_call(string milk\pureentities\entity\monster\flying\Blaze)
#1 /src/pocketmine/entity/Entity(452): ReflectionClass->__construct(string milk\pureentities\entity\monster\flying\Blaze)
#2 /EntityManagerv2.7.phar/src/milk/entitymanager/EntityManager(84): pocketmine\entity\Entity::registerEntity(string milk\pureentities\entity\monster\flying\Blaze)
#3 /src/pocketmine/plugin/PharPluginLoader(65): milk\entitymanager\EntityManager->__construct(boolean)
#4 /src/pocketmine/plugin/PluginManager(155): pocketmine\plugin\PharPluginLoader->loadPlugin(string phar:///home/minecraft/multicraft/servers/server1453/plugins/EntityManagerv2.7.phar)
#5 /src/pocketmine/plugin/PluginManager(301): pocketmine\plugin\PluginManager->loadPlugin(string /home/minecraft/multicraft/servers/server1453/plugins/EntityManagerv2.7.phar, array Array())
#6 /src/pocketmine/Server(1934): pocketmine\plugin\PluginManager->loadPlugins(string /home/minecraft/multicraft/servers/server1453/plugins/)
#7 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/servers/server1453/imagicalmine_0_14_0_PHP7.phar/, string /home/minecraft/multicraft/servers/server1453/, string /home/minecraft/multicraft/servers/server1453/plugins/)
#8 (1): require_once(string phar:///home/minecraft/multicraft/servers/server1453/imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php)

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Linux mc12 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0

**Comment by LeinneSW** [comment]
idk why this bug happens

**Comment by Erkam246** [comment]
Pls fix it

**Comment by LeinneSW** [comment]
This is not a bug that I created
IDK how to fix it

**Comment by Erkam246** [comment]
;'(

**Comment by Erkam246** [comment]
I thing that is a bug from Entitymanager i have only the PureEntitys Plugin and that go but when i make Entitymanager in my server it go not more 

Sry for my nad english xD

**Comment by LeinneSW** [comment]
No, it just couldn't find Blaze file

**Comment by Erkam246** [comment]
But it ho with only PureEntitys

**Comment by LeinneSW** [comment]
??
i don't understand

**Comment by Erkam246** [comment]
When i have only PureEntitys work it but with Entitymanager not

**Comment by LeinneSW** [comment]
oh, sorry this is not pe bug
this is em bug
i fixed it soon

**Comment by Erkam246** [comment]
Thx

**Comment by LeinneSW** [comment]
fixed
