### ISSUE TITLE
Feature: Feed animals

### ISSUE THREAD

**Issue by jigamiller** [LeinneSW/PureEntities#50]
Not sure if this is part of the plugin or in the core. My kids love the creative mode but one of their favorite parts is feeding the animals so I can't get them to use the server until I find someway to get this to work.
#### Issue description

Unable to "Feed" animals
#### Steps to reproduce the issue

Spawn a pig
Select a carrot and get next to the pig until "Feed" button shows
Click "Feed"

In normal game - hearts show up when you feed them.
#### version

v 1.0

**Comment by inxomnyaa** [comment]
(Action interact packet, Action: right click.)
Maybe this helps the dev.

The hearts a tag like NoAI.. i'll search the numbers

**Comment by LeinneSW** [comment]
Feeding will be fixed later.
