### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by PoilZero** [LeinneSW/PureEntities#53]
Enitity don't know to jump.

**Comment by Sandertv** [comment]
Yeah same problem here.

**Comment by inxomnyaa** [comment]
:sweat_smile: uhm.. yeaaa. This project is not continued.

**Comment by Sandertv** [comment]
Yeah I know... too badly, I think it's the best Mob AI out there.

**Comment by inxomnyaa** [comment]
May try to improve on my repo

**Comment by Sandertv** [comment]
Would be epic, kinda sucks if such a plugin would go to a waste
