### ISSUE TITLE
May I upload this to ImagicalMine forums?

### ISSUE THREAD

**Issue by DarkWav** [LeinneSW/PureEntities#56]
I was often asked on ImagicalMine Forums for a plugin wich implements a mob AI.
So, may I upload this plugin to ImagicalMine?
What I WON´T do Is:

-modyfying the code.
-say I´m the author.
-trying to get money with this.

I will of course link to this github repositry and credit the author.
Thanks, Darku

**Comment by Erkam246** [comment]
Can you german?

**Comment by inxomnyaa** [comment]
:D *speak german

**Comment by Erkam246** [comment]
xD

**Comment by Erkam246** [comment]
@thebigsmileXD

**Comment by DarkWav** [comment]
Yes I can speak german. (Ja, ich kann deuthsch sprechen.)

**Comment by jdot-r** [comment]
I just use google translate

**Comment by jdot-r** [comment]
meh
