### ISSUE TITLE
Drops Problem

### ISSUE THREAD

**Issue by kaitododoyt** [LeinneSW/PureEntities#57]
I cant consume dropped food

**Comment by inxomnyaa** [comment]
Core issue

**Comment by PoilZero** [comment]
2 months did not update the author abandoned pit @thebigsmileXD @HmHmmHm @milk0417 @erkam2002

**Comment by HmHmmHm** [comment]
@ibookcc hmm.. he is so busy, if you tell me about what's need, so i'll send him

**Comment by LeinneSW** [comment]
Item drop will be fixed later.
