### ISSUE TITLE
I tidy up all of the current bug

### ISSUE THREAD

**Issue by PoilZero** [LeinneSW/PureEntities#58]
1. Creatures can not jump, which can not be
2. Creatures will not be automatically generated
3. The hell monster's attack is just an explosion and there's no physical display.

**Comment by HmHmmHm** [comment]
1. What kinds of? all of them?
2. Have you checked your nukkit? is this problem about new nukkit api?
3. I'll check that problem

**Comment by zzz1999** [comment]
可以很强势 @ibookcc

**Comment by LeinneSW** [comment]
sorry, but this project is depercated
