### ISSUE TITLE
Add more mobs. [0.15.0]

### ISSUE THREAD

**Issue by EnderKenji** [LeinneSW/PureEntities#59]
Like, horses, Stray, witch and more.

**Comment by LeinneSW** [comment]
죄송하지만, PMMP버전은 지원이 중단되었습니다
[PE-Nukkit](https://github.com/SW-Team/PureEntities)만 개발중입니다

**Comment by inxomnyaa** [comment]
@milk0417 uhm, but he asked in english i guess

> Sorry, PMMP version is deprecated
> PE-Nukkit only being developed

**Comment by EnderKenji** [comment]
Why ;-; 

Really need this ;-;

**Comment by LeinneSW** [comment]
@thebigsmileXD No bukkit
[Nukkit](github.com/Nukkit/Nukkit)
