### ISSUE TITLE
Just some suggestions...

### ISSUE THREAD

**Issue by jerryzooyoyo** [LeinneSW/PureEntities#6]
Well, first of all, great plugin I've never seen !
Most of the server owners are using API 1.x.x, included me.
So I want that this plugin could be used in API 1.x.x, AGAIN !
Before you updated this plugin into API 2.0.0, I had used this great plugin for a long time.
Could you let this plugin run in 2 APIs ?
Or just make the old API version AGAIN ?
Thanks, sorry for my bad English...

**Comment by LeinneSW** [comment]
미안해요, 전 더이상 PMMP 개발을 하지 않아요
I'm sorry, I do not anymore PMMP development
