### ISSUE TITLE
Why is this Deprecated? It's the only way to get truly functional mobs on pocketmine.

### ISSUE THREAD

**Issue by DaMatrix** [LeinneSW/PureEntities#61]

**Comment by inxomnyaa** [comment]
https://github.com/milk0417/PureEntities/blob/master/README.md
https://github.com/milk0417/PureEntities/issues/59

**Comment by DaMatrix** [comment]
But the other one is for nukkit. I'm talking about pocketmine and dereitives.

**Comment by inxomnyaa** [comment]
He does work on other things

**Comment by LeinneSW** [comment]
sorry but i hate php

**Comment by DaMatrix** [comment]
:(

-------- Original message --------
