### ISSUE TITLE
몬스터가 점프를 못합니다

### ISSUE THREAD

**Issue by shdudwns** [LeinneSW/PureEntities#62]
![screenshot_2018-01-06-11-25-38](https://user-images.githubusercontent.com/26038520/34635547-93cdbee8-f2d4-11e7-8c09-e40be0240e1b.png)

**Comment by LeinneSW** [comment]
점프는 특정각도에서 잘 안되는게 확인되었으며, 계속 개선중에 있습니다

**Comment by LeinneSW** [comment]
수정 완료
