### ISSUE TITLE
몹스포너 클리시 오류

### ISSUE THREAD

**Issue by shdudwns** [LeinneSW/PureEntities#67]
18:14:04 CRITICAL > 이벤트 'pocketmine\event\player\PlayerInteractEvent'을(를) 'PureEntities v1.0.0'에 전달하지 못했습니다: milk\pureentities\PureEntities에서의 Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported
18:14:04 CRITICAL > RuntimeException: "Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported" (EXCEPTION) in "vendor/pocketmine/pocketmine-nbt/src/tag/NoDynamicFieldsTrait" at line 29

**Comment by shdudwns** [comment]
설치시 바로크덤

Error: Expected a tag of type pocketmine\nbt\tag\ShortTag, got pocketmine\nbt\tag\IntTag
File: vendor/pocketmine/pocketmine-nbt/src/tag/CompoundTag
Line: 107
Type: RuntimeException

**Comment by shdudwns** [comment]
@LeinneSW

**Comment by LeinneSW** [comment]
ㅎㄱㄱ
조금만 기달려 보심시오

**Comment by shdudwns** [comment]
@LeinneSW ㅎㄱㄱ
