### ISSUE TITLE
Server get crash wenn player kill mobs - i have Altay 1.2.11

### ISSUE THREAD

**Issue by dennisslol006** [LeinneSW/PureEntities#69]
22:54:55 DEBUG > #0 vendor/pocketmine/nbt/src/tag/CompoundTag(309): pocketmine\nbt\tag\CompoundTag->getTag(string EntityId, string pocketmine\nbt\tag\ShortTag)
22:54:55 DEBUG > #1 vendor/pocketmine/nbt/src/tag/CompoundTag(336): pocketmine\nbt\tag\CompoundTag->setTagValue(string EntityId, string pocketmine\nbt\tag\ShortTag, integer 13, boolean )
22:54:55 DEBUG > #2 PureEntities by Denniss/src/milk/pureentities/tile/Spawner(100): pocketmine\nbt\tag\CompoundTag->setShort(string EntityId, integer 13)
22:54:55 DEBUG > #3 src/pocketmine/level/format/io/region/Anvil(79): milk\pureentities\tile\Spawner->saveNBT()
22:54:55 DEBUG > #4 src/pocketmine/level/format/io/region/McRegion(375): pocketmine\level\format\io\region\Anvil->nbtSerialize(pocketmine\level\format\Chunk object)
22:54:55 DEBUG > #5 src/pocketmine/level/format/io/BaseLevelProvider(133): pocketmine\level\format\io\region\McRegion->writeChunk(pocketmine\level\format\Chunk object)
22:54:55 DEBUG > #6 src/pocketmine/level/Level(2802): pocketmine\level\format\io\BaseLevelProvider->saveChunk(pocketmine\level\format\Chunk object)
22:54:55 DEBUG > #7 src/pocketmine/level/Level(443): pocketmine\level\Level->unloadChunk(integer 26, integer 14, boolean )
22:54:55 DEBUG > #8 src/pocketmine/level/Level(579): pocketmine\level\Level->close()
22:54:55 DEBUG > #9 src/pocketmine/Server(1010): pocketmine\level\Level->unload(boolean 1)
22:54:55 DEBUG > #10 src/pocketmine/Server(2092): pocketmine\Server->unloadLevel(pocketmine\level\Level object, boolean 1)
22:54:55 DEBUG > #11 src/pocketmine/Server(2284): pocketmine\Server->forceShutdown()
22:54:55 DEBUG > #12 src/pocketmine/Server(2219): pocketmine\Server->crashDump()
22:54:55 DEBUG > #13 src/pocketmine/Server(1762): pocketmine\Server->exceptionHandler(RuntimeException object)
22:54:55 DEBUG > #14 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Denniss\Desktop\PocketMine-MP\, string C:\Users\Denniss\Desktop\PocketMine-MP\plugins\)
22:54:55 DEBUG > #15 C:/Users/Denniss/Desktop/PocketMine-MP/PocketMine-MP.phar(1): require_once(string phar://C:/Users/Denniss/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by shdudwns** [comment]
Do you use old version?

**Comment by dennisslol006** [comment]
is a new version 1.2.13 and is this error 22:54:55 DEBUG > #0 vendor/pocketmine/nbt/src/tag/CompoundTag(309): pocketmine\nbt\tag\CompoundTag->getTag(string EntityId, string pocketmine\nbt\tag\ShortTag)
22:54:55 DEBUG > #1 vendor/pocketmine/nbt/src/tag/CompoundTag(336): pocketmine\nbt\tag\CompoundTag->setTagValue(string EntityId, string pocketmine\nbt\tag\ShortTag, integer 13, boolean )
22:54:55 DEBUG > #2 PureEntities by Denniss/src/milk/pureentities/tile/Spawner(100): pocketmine\nbt\tag\CompoundTag->setShort(string EntityId, integer 13)
22:54:55 DEBUG > #3 src/pocketmine/level/format/io/region/Anvil(79): milk\pureentities\tile\Spawner->saveNBT()
22:54:55 DEBUG > #4 src/pocketmine/level/format/io/region/McRegion(375): pocketmine\level\format\io\region\Anvil->nbtSerialize(pocketmine\level\format\Chunk object)
22:54:55 DEBUG > #5 src/pocketmine/level/format/io/BaseLevelProvider(133): pocketmine\level\format\io\region\McRegion->writeChunk(pocketmine\level\format\Chunk object)
22:54:55 DEBUG > #6 src/pocketmine/level/Level(2802): pocketmine\level\format\io\BaseLevelProvider->saveChunk(pocketmine\level\format\Chunk object)
22:54:55 DEBUG > #7 src/pocketmine/level/Level(443): pocketmine\level\Level->unloadChunk(integer 26, integer 14, boolean )
22:54:55 DEBUG > #8 src/pocketmine/level/Level(579): pocketmine\level\Level->close()
22:54:55 DEBUG > #9 src/pocketmine/Server(1010): pocketmine\level\Level->unload(boolean 1)
22:54:55 DEBUG > #10 src/pocketmine/Server(2092): pocketmine\Server->unloadLevel(pocketmine\level\Level object, boolean 1)
22:54:55 DEBUG > #11 src/pocketmine/Server(2284): pocketmine\Server->forceShutdown()
22:54:55 DEBUG > #12 src/pocketmine/Server(2219): pocketmine\Server->crashDump()
22:54:55 DEBUG > #13 src/pocketmine/Server(1762): pocketmine\Server->exceptionHandler(RuntimeException object)
22:54:55 DEBUG > #14 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Denniss\Desktop\PocketMine-MP, string C:\Users\Denniss\Desktop\PocketMine-MP\plugins)
22:54:55 DEBUG > #15 C:/Users/Denniss/Desktop/PocketMine-MP/PocketMine-MP.phar(1): require_once(string phar://C:/Users/Denniss/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by LeinneSW** [comment]
I have not found any errors in any of the statements.
DEBUG is not an error.
Please bring a normal error message.
