### ISSUE TITLE
괴물 스 포 너

### ISSUE THREAD

**Issue by splexpe** [LeinneSW/PureEntities#73]
이 수정 마피아 스 포 너 메타 id (52:20 골 렘 등)

**Comment by splexpe** [comment]
@LeinneSW

**Comment by LeinneSW** [comment]
please english

**Comment by splexpe** [comment]
This fix monster spawners? Meta ID (52:20 golem, etc.)

(also I thought you spoke korean)
@LeinneSW

**Comment by LeinneSW** [comment]
I am Korean, but the sentence is completely wrong.
What is the specific problem with the Golem spawn?

**Comment by splexpe** [comment]
Nothing with the IG spawn,
Im asking if this plugin fixes monsterspawners?
(teaspoon isnt supported for 3.6.2 rn)

**Comment by LeinneSW** [comment]
sry, but I can't understand the question.

**Comment by jasonw4331** [comment]
@splexpe is asking if mob spawners work in this plugin

**Comment by LeinneSW** [comment]
Yes. It works well.
