### ISSUE TITLE
How find i the PM version with api 2.0.0

### ISSUE THREAD

**Issue by Erkam246** [LeinneSW/PureEntities#8]
can you help me or pls compatible with api 0.14.0 or 0.13.0?

**Comment by DarkWav** [comment]
# 

# to use this plugin, you have to download the master , edit plugin.yml and recompile it.

# plugin.yml looks like this:

#name, main, version and api are required
name: EntityManager
main: milk\entitymanager\EntityManager
version: "2.4 Beta"
api: 2.0.0
load: POSTWORLD
author: ìš°ìœ ë§›ë¹„ëˆ„
commands:
 entitymanager:
  usage: false
  description: ""
  aliases: [ent, entity]
  permission: entitymanager.command

# but you have to change it to that:

#name, main, version and api are required
name: EntityManager
main: milk\entitymanager\EntityManager
version: "2.4 Beta"
api: 1.14.0
load: POSTWORLD
author: ìš°ìœ ë§›ë¹„ëˆ„
commands:
 entitymanager:
  usage: false
  description: ""
  aliases: [ent, entity]
  permission: entitymanager.command

# Than you can put the "src" folder and the modyfied plugin.yml into a zip file and compile it for exaple here: http://pmt.mcpe.me/. If you want API 1.13.0 it shold look like this:

#name, main, version and api are required
name: EntityManager
main: milk\entitymanager\EntityManager
version: "2.4 Beta"
api: 1.13.0
load: POSTWORLD
author: ìš°ìœ ë§›ë¹„ëˆ„
commands:
 entitymanager:
  usage: false
  description: ""
  aliases: [ent, entity]
  permission: entitymanager.command

**Comment by Erkam246** [comment]
Not work ImagicalMine Crash Dump Sat Jan 23 16:04:04 GMT 2016

Error: syntax error, unexpected ':', expecting ';' or '{'
File: /phar_EntityManager-master_q7SjyA11rJKsnbc.phar/src/milk/entitymanager/entity/Monster
Line: 27
Type: E_PARSE

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[18]     private $minDamage = [0, 0, 0, 0];
[19]     private $maxDamage = [0, 0, 0, 0];
[20] 
[21]     private $entityTick = 0;
[22] 
[23]     protected $attackDelay = 0;
[24] 
[25]     public abstract function attackEntity(Entity $player);
[26] 
[27]     public function getDamage($difficulty = null) : float{
[28]         return mt_rand($this->getMinDamage($difficulty), $this->getMaxDamage($difficulty));
[29]     }
[30] 
[31]     public function getMinDamage($difficulty = null) : float{
[32]         if($difficulty === null or !is_numeric($difficulty) || $difficulty > 3 || $difficulty < 0){
[33]             $difficulty = Server::getInstance()->getDifficulty();
[34]         }
[35]         $difficulty = (int) $difficulty;
[36]         return $this->minDamage[$difficulty];
[37]     }

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/spl/BaseClassLoader(11): BaseClassLoader->loadClass(boolean)
#2 /src/spl/BaseClassLoader(11): spl_autoload_call(boolean)
#3 /src/spl/BaseClassLoader(128): (boolean)
#4 /phar_EntityManager-master_q7SjyA11rJKsnbc.phar/src/milk/entitymanager/EntityManager(289): BaseClassLoader->loadClass(boolean)
#5 /phar_EntityManager-master_q7SjyA11rJKsnbc.phar/src/milk/entitymanager/EntityManager(289): spl_autoload_call(boolean)
#6 /phar_EntityManager-master_q7SjyA11rJKsnbc.phar/src/milk/entitymanager/EntityManager(289): ReflectionClass->__construct(boolean)
#7 /phar_EntityManager-master_q7SjyA11rJKsnbc.phar/src/milk/entitymanager/EntityManager(99): milk\entitymanager\EntityManager::registerEntity(boolean)
#8 /src/pocketmine/plugin/PharPluginLoader(70): milk\entitymanager\EntityManager->__construct(boolean)
#9 /src/pocketmine/plugin/PluginManager(157): pocketmine\plugin\PharPluginLoader->loadPlugin(boolean)
#10 /src/pocketmine/plugin/PluginManager(301): pocketmine\plugin\PluginManager->loadPlugin(boolean)
#11 /src/pocketmine/Server(1745): pocketmine\plugin\PluginManager->loadPlugins(boolean)
#12 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(boolean)
#13 (1): (boolean)
#14 (0): {main}(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT KAHRAMAN-PC 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1

**Comment by Erkam246** [comment]
oh  i have that fix but a new error : error> Could not load plugin 'EntityManager': Incompatible API version

**Comment by PocketKiller** [comment]
you need PHP7

**Comment by Erkam246** [comment]
how find i that?

**Comment by PocketKiller** [comment]
we are working on a PHP7 Rewrite for ImagicalMine, but you can still get Genisys with PHP7

**Comment by NickelBlack** [comment]
Good. Already use genisys)

**Comment by Erkam246** [comment]
Ok

**Comment by LeinneSW** [comment]
It works only in PHP7

**Comment by Erkam246** [comment]
How find i php7?

**Comment by LeinneSW** [comment]
hmm... Why dont you search on Google?

**Comment by Erkam246** [comment]
Have i already i havent found that pls link url

**Comment by LeinneSW** [comment]
I'm sorry, I do not have a url. I dont use the PMMP

**Comment by DarkWav** [comment]
https://secure.php.net/downloads.php

**Comment by DarkWav** [comment]
this link shold work
